### ISSUE TITLE
US1

### ISSUE THREAD

**Issue by matschi3** [matschi3/testarea#1]
## Value Proposition

**As a** user  
**I want to** view a list of parts  
**so that** i have an overview on parts
​

## Description

![Image](https://user-images.githubusercontent.com/114819127/247908298-09b9df2c-01a7-4e9f-b113-adc5164efe67.png)   

## Acceptance Criteria

- [ ] user can see a list of all parts with basic partData
- [ ] listItems have same size
- [ ] listItems width almost screenWidth
- [ ] list scrolls vertically
- [ ] heading is always visible
      ​

## Tasks

- [ ] create branch 
- [ ] create dummy Partsdata
- [ ] display PartsData on FrontEnd
- [ ] create global styles
- [ ] create basic partCard style
      ​

**Comment by matschi3** [comment]
die einzelnen partCards können aber schon alles beinhalten, was später auch drauf sein soll, oder? :)

**Comment by julialoeschel** [comment]
Hey Nils :) 
Sehr gute Story :) 
die partCards sollten auch erstmal noch simpel sein, ich weiß zB nicht aus der Story, was die orangen und grauen Kästen sind. brauchen wir die schon? 
Ich würde sagen Name, Preis und foto reicht schon, kathegorie kann natürlich auch mit drauf. (kann es mehrere Kathegoriern geben, wie schaut das dann aus?)

Sonst super! Weiter so!

**Comment by matschi3** [comment]
danke :) 
ja, jedes Teil soll nur eine Kategorie haben.
Und die beiden Kästchen sind einmal (grau) ein Status, der seine Farbe bei bestimmten Werten ändert und das andere (gelbe) soll so ein toggleButton sein.
Ich würde die beiden dann erstmal rausnehmen für die US1.
Die Kategorie bleibt ohne Funktion also lass ich dir drin.

**Comment by matschi3** [comment]
also ich dachte ganz am Anfang, dass es mehrere Kategorien werden; macht im Kontext aber gar keinen Sinn

**Comment by julialoeschel** [comment]
Sieht super aus, good to go!
